name: Close PRs to Main

# Trigger the action when a pull request is opened or edited
on:
  pull_request:
    branches:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close PR to main branch
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "Please submit this PR to the `test` branch, not `main`."
